# Development CI
-
  branches:
    except:
      - master
  version: 0.1.0.{build}
  os: Visual Studio 2015
  configuration: Debug
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  environment:
    COVERALLS_REPO_TOKEN:
      secure: pJSh3uNVX95c4AMMnIWH6fy6EX8nywcfbgi2WqbuwYaWS6JQMHy6WFX0foQM4iHl
  before_build:
  - cmd: nuget restore src\Pistons.sln
  build:
    project: src\Pistons.sln
    verbosity: minimal
  test_script:
  - cmd: >-
      src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:src\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe -targetargs:"src\En.Gen.Pistons.Tests\bin\debug\En.Gen.Pistons.Tests.dll -noshadow -appveyor" -filter:"+[En.Gen.*]* -[*.Tests]*" -output:coverage.xml
      src\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
  notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
  
# Release CI
-
  branches:
    only:
      - master
  version: 0.1.0.{build}
  os: Visual Studio 2015
  configuration: Release
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  environment:
    COVERALLS_REPO_TOKEN:
      secure: pJSh3uNVX95c4AMMnIWH6fy6EX8nywcfbgi2WqbuwYaWS6JQMHy6WFX0foQM4iHl
  before_build:
  - cmd: nuget restore src\Pistons.sln
  build:
    project: src\Pistons.sln
    verbosity: minimal
  test_script:
  - cmd: >-
      src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:src\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe -targetargs:"src\En.Gen.Pistons.Tests\bin\debug\En.Gen.Pistons.Tests.dll -noshadow -appveyor" -filter:"+[En.Gen.*]* -[*.Tests]*" -output:coverage.xml
      src\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
  notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
